# Comes from https://github.com/Swarsel/.dotfiles/blob/main/.github/workflows/flake-checks.yaml

name: Flake check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths-ignore:
      - '.github/**' # Avoid issues with Dependabot
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  flake-check:
    name: Check flake
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Use Magic Nix Cache to cache builds between workflows
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
        with:
          fail-mode: true
          check-outdated: false # update.yaml should take care of this
      - name: Check for dead code in .nix files
        run: git ls-files '*.nix' | nix run nixpkgs#deadnix
        continue-on-error: true
      - name: Check for lints in .nix files
        run: nix run nixpkgs#statix -- check
        continue-on-error: true
      - name: Check formatting in .nix files
        run: git ls-files '*.nix' | xargs nix run nixpkgs#nixfmt -- --check
        continue-on-error: true
      - name: Check whether the flake builds
        run: nix flake check --all-systems --keep-going --debug .
