name: "Build images and create GitHub Release draft for new versions"

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - architecture: x86_64
            os: ubuntu-24.04
          - architecture: aarch64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v7
      - name: "Install Nix"
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:26.05
          extra_nix_config: |
            system-features = nixos-test benchmark big-parallel kvm uid-range
      - name: Build images
        run: >
          nix run github:nixos/nixpkgs/nixos-unstable#nixos-rebuild --
          build-image --image-variant qemu-efi --flake .#${{ matrix.architecture }}
      - name: Copy and rename generated qcow2 file to reflect version and architecture
        run: |
          REAL_QCOW2_FILENAME=$(readlink -f $(find result/ -name "nixos-*.qcow2" -print -quit))
          cp "$REAL_QCOW2_FILENAME" \
            nixos-cloud-init-installer-${{ github.ref_name }}-${{ matrix.architecture }}.qcow2
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: qcow2-artifact-${{ matrix.architecture }}
          path: nixos-cloud-init-installer-${{ github.ref_name }}-${{ matrix.architecture }}.qcow2
  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: qcow2-artifacts
          pattern: qcow2-artifact-*
          merge-multiple: true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: qcow2-artifacts/*.qcow2
