# Comes from https://github.com/god464/flake/blob/master/.github/workflows/update.yml

name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 0' # Every Sunday at 12:00 PM

permissions:
  pull-requests: write
  contents: write

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1 # v13
        with:
          fail-mode: true
          check-outdated: false # This is the workflow for updating...
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@834c491b2ece4de0bbd00d85214bb5e83b4da5c6 # v28
        with:
          commit-msg: 'bump(lock): Update flake.lock'
          pr-title: 'bump(lock): Update flake.lock'
